### ISSUE TITLE
Security group egress missing

### ISSUE THREAD

**Issue by ldormoy** [cloudposse/terraform-aws-ec2-bastion-server#19]
The security group *egress {}* is missing, so the bastion instance can't actually reach any private IP address.

Did you maybe mean this to be an egress?
https://github.com/cloudposse/terraform-aws-ec2-bastion-server/blob/master/main.tf#L55

**Comment by jwstric2** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group

```
By default, AWS creates an ALLOW ALL egress rule when creating a new Security Group inside of a VPC. When creating a new Security Group inside a VPC, Terraform will remove this default rule, and require you specifically re-create it if you desire that rule. We feel this leads to fewer surprises in terms of controlling your egress rules. If you desire this rule to be in place, you can use this egress block:
```

Not sure if this has always been true but definately agree with @ldormoy  (even though old issue).  It also impacts that cloud-init can not be ran to install other packages (except creating AMI first).
