### ISSUE TITLE
Make creation depend on a parameter

### ISSUE THREAD

**Issue by mhvelplund** [cloudposse/terraform-aws-ec2-bastion-server#20]
It would be nice to be able to disable bastion creation by setting a parameter on the module, e.g. "create = false":

```hcl
module "ec2-bastion-server" {
  source  = "cloudposse/ec2-bastion-server/aws"
  version = "0.2.7"
  create  = false
  ...
}
```

**Comment by DeividasJackus** [comment]
This issue can be closed as this is achievable using the `enabled` variable.
