### ISSUE TITLE
Add Terraform v0.12 Support

### ISSUE THREAD

**Issue by dmattia** [cloudposse/terraform-aws-ec2-bastion-server#24]
I would be willing to update this if you'd like

**Comment by kuritonasu** [comment]
There are already PRs for this, that have their CIs failing due to running tests on TF 11.x

**Comment by kuritonasu** [comment]
@aknysh tagging you if I may, as cloudposse might not be monitoring this space. Could one of the 0.12.x PRs be merged, in order to make this module TF .12 compatible? Apologies in advance if I'm generating extra unnecessary noise, and thank you in advance.

**Comment by osterman** [comment]
Closed by #27 which adds 0.12 support with tests
