### ISSUE TITLE
AMI will always upgrade

### ISSUE THREAD

**Issue by razorsedge** [cloudposse/terraform-aws-ec2-bastion-server#68]
## Describe the Bug
As of version 0.25.0, AMIs are dynamically sourced and will force redeployment of this EC2 instance resource whenever the AMI is found to be updated.
```
data "aws_ami" "default" {
  most_recent = "true"
...
```

## Expected Behavior
Bastion host should be redeployed when *I* determine and not the AMI creator.

## Additional Context
Perhaps use an optional `ignore_changes`?
```
  lifecycle {
    ignore_changes = [
      ami,
    ]
  }
```

**Comment by nitrocode** [comment]
The easy fix is to ignore ami. I think the best method is to use an asg and a launch template to define the ami. If the ami updates, then we can update the launch template which would prevent updating the existing ec2 instance.

**Comment by nitrocode** [comment]
actually you can use a filter to pin the ami

https://github.com/cloudposse/terraform-aws-ec2-bastion-server/blob/702027453501ff663d6978e65ce87f58499a3638/main.tf#L17-L23

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami#filter

https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html#options

> image-id - The ID of the image.

```hcl
module "ec2_bastion" {
  source  = "cloudposse/ec2-bastion-server/aws"
  version = "0.27.0"

  ami_filters = {
    "image-id" = "ami-1234567890"
  }

  instance_type               = var.instance_type
  security_groups             = compact(concat([module.vpc.vpc_default_security_group_id], var.security_groups))
  subnets                     = module.subnets.public_subnet_ids
  key_name                    = module.aws_key_pair.key_name
  user_data                   = var.user_data
  vpc_id                      = module.vpc.vpc_id
  associate_public_ip_address = var.associate_public_ip_address

  context = module.this.context
}
```
